language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
branches:
  only:
    - master
script:
  - cargo test --verbose
notifications:
  email:
    on_success: never
